Update dart.yml

diff --git a/.github/workflows/dart.yml b/.github/workflows/dart.yml
--- a/.github/workflows/dart.yml
+++ b/.github/workflows/dart.yml
@@ -5,49 +5,55 @@ on:
 
 jobs:
   build-ios:
-    name: 🎉 iOS Build
     runs-on: macos-latest
     steps:
       - uses: actions/checkout@v3
 
-      - name: 🛠️ Fix iOS Build Permissions
+      - uses: subosito/flutter-action@v2
+        with:
+          channel: stable
+          architecture: x64
+
+      - name: Install Dependencies
+        run: flutter pub get
+
+      - name: Clean Project
+        run: flutter clean
+
+      - name: Install CocoaPods
+        run: |
+          cd ios
+          pod install --repo-update
+
+      - name: First Build Pass (creates build folder)
+        run: flutter build ios --release --no-codesign || true  # ignore failure for now
+
+      - name: Fix Permissions
         run: |
           chmod -R 777 ios
           chmod -R 777 build
-          chmod -R 777 build/ios
 
-      - uses: subosito/flutter-action@v2
-        with:
-          channel: 'stable'
-          architecture: x64
-      - run: flutter pub get
-      
+      - name: Build iOS App
+        run: flutter build ios --release --no-codesign
 
-      - run: pod repo update
-        working-directory: ios
-
-      - name: Build iOS archive
+      - name: Archive iOS App
         run: |
-          flutter build ios --release --no-codesign
           xcodebuild -workspace ios/Runner.xcworkspace \
             -scheme Runner \
             -configuration Release \
             -sdk iphoneos \
-            -archivePath build/ios/archive/Runner.xcarchive \
+            -archivePath build/Runner.xcarchive \
             archive
 
       - name: Export IPA
         run: |
           xcodebuild -exportArchive \
-            -archivePath build/ios/archive/Runner.xcarchive \
+            -archivePath build/Runner.xcarchive \
             -exportOptionsPlist ios/ExportOptions.plist \
             -exportPath build/ios/ipa
 
-      - name: Upload binaries to release
-        uses: svenstaro/upload-release-action@v2
+      - name: Upload IPA
+        uses: actions/upload-artifact@v4
         with:
-          repo_token: ${{ secrets.GITHUB_TOKEN }}
-          file: build/ios/ipa/Runner.ipa
-          tag: v1.0
-          overwrite: true
-          body: "This is first release"
+          name: iOS_Unsigned_IPA
+          path: build/ios/ipa/*.ipa
